(#1): Configuração do ambiente local para executar projeto
ResidenciaTICBrisa/T2G8-Plugin-Wordpress pull request #2
Opened 2024-03-04 16:33 UTC by WillxBernardo

2024-03-04 21:25 UTC, Max-Rohrer20 approved these changes

2024-03-04 21:33 UTC, Punkrig approved these changes

2024-03-05 13:05 UTC, Max-Rohrer20 requested changes
Falta configurar o volume do WordPress

2024-03-05 13:07 UTC, Punkrig reviewed
Esta faltando fazer a configuração do wordpress

2024-03-05 13:09 UTC, Punkrig requested changes
Está faltando fazer as configurações do wordpress

2024-03-05 17:17 UTC, Max-Rohrer20 approved these changes

2024-03-05 17:18 UTC, Punkrig approved these changes

2024-03-05 20:08 UTC, merged